openapi: 3.0.0
title: STD24050
version: 1.0.0
description: "This is a specification of STD24050"
servers:
  - url: http://localhost:8000

paths:
  components:
    schemas:
      component:
        type: object
        properties:
          id:
            type: string
          name:
            type: string
        required:
          - id
          - name