openapi: 3.0.0
info:
  title: STD24050
  version: 1.0.0
  description: "This is a specifcation of STD24050"
paths:
  /components:
    get:
      summary: "Get components"
      responses:
        '200':
          description: "A list of components"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string